baseURL = "https://tum.pt"
disqusShortname = ""
languageCode = "pt-pt"
paginate = "5"
summaryLength = "10"
theme = "northendlab-hugo"
title = "Tuna Universitária do Minho"
[[menu.footer]]
URL = "tools"
name = "tools"
parent = "Contact"
weight = 1
[[menu.footer]]
URL = "contact"
name = "Contact"
weight = 1
[[menu.main]]
URL = "elementos"
name = "Elementos"
parent = "Sobre a TUM"
weight = 3
[[menu.main]]
URL = "espetaculos"
name = "Espetáculos e Prémios"
parent = "Sobre a TUM"
weight = 1
[[menu.main]]
name = "Sobre a TUM"
weight = 2
[[menu.main]]
URL = "fitus"
name = "FITU Bracara Avgvsta"
weight = 1
[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]
[params]
author = "Themefisher"
contact_form_action = "#"
copyright = "&copy; [Tuna Universitária do Minho](/) All Rights Reserved"
description = "This is meta description"
google_analitycs_id = ""
google_tag_manager = ""
home = "Início"
logo = "images/logo.svg"
[params.banner]
bgImage = "images/banner/banner-bg.svg"
image = "images/banner/illustration.svg"
title = "Hi, I'm John Smith Doe. <br> I help people make the  worlds best software"
[params.cta]
description = "Ensaios todas as terças e quinta-feiras por baixo do BA às 21:30"
enable = true
icon = "fas fa-running"
image = "/images/bandeira.gif"
title = "Queres pertencer à Tuna Universitária do Minho? "
[params.cta.button]
enable = true
label = "Contacta-nos"
link = "/contact"
[params.cta2]
description = "Em breve novidades sobre a próxima edição do festival"
enable = true
icon = "fas fa-guitar"
image = "/images/fitu.jpg"
title = "FITU Bracara Avgvsta"
[params.cta2.button]
enable = false
label = "Visit Here"
link = "https://gethugothemes.com/shop/"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
[params.search]
enable = false
[[params.homepageimage]]
descricao = "Passagem a Tuno em 1998"
url = "/uploads/passagem_a_tuno_1998.JPG"
[[params.homepageimage]]
descricao = "Retiro no Gerês em 1995"
url = "/uploads/tum_retiro_geres_1995.JPG"
[[params.homepageimage]]
descricao = "Estreia - Enterro da Gata 1990"
url = "/uploads/estreia_tum.jpg"
[[params.homepageimage]]
descricao = "E o Gerês me carregou a alma"
url = "/images/tum1.jpg"
[[params.social]]
icon = "fab fa-facebook-f"
link = "https://www.facebook.com/tunauniversitariaminho"
[[params.social]]
icon = "fab fa-instagram"
link = "https://www.instagram.com/tunauniversitariadominho"
[[params.social]]
icon = "fab fa-youtube"
link = "https://www.youtube.com/channel/UClj56MMgzqLuCQSa4Ege6nQ"
[[params.social]]
icon = "fab fa-spotify"
link = "https://open.spotify.com/artist/7nEqs0isAyEONxQbPrVRgb?autoplay=true&v=A"
